### ISSUE TITLE
Can you use youtube-dl to bypass yt apis?

### ISSUE THREAD

**Issue by UmutAlihan** [XiovV/Golty#1]

**Comment by XiovV** [comment]
I have tried using some youtube-dl wrappers but had issues with them, but still definitely on my list.

**Comment by XiovV** [comment]
I am currently working on my own youtube-dl wrapper but I'm having some issues.

`out, err := exec.Command("youtube-dl", "-j", "--playlist-start 1", "--playlist-end 1", channelURL).Output()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("output: %s\n", out)`

Returns exit status code 2

**Comment by XiovV** [comment]
I am working on my own youtube-dl wrapper now.

**Comment by XiovV** [comment]
youtube-dl implementation is done
