### ISSUE TITLE
A few useful features

### ISSUE THREAD

**Issue by xInsertx** [XiovV/Golty#20]
Project looks good, but a few useful things could make it great.

Naming Convention field, for path / file format.
Single Playlist support, for monitoring a single playlist.
Detect Playlists on a Channel, and allow selecting which ones to monitor.
Simple database (SQLite) just to track video download history (could be used to prevent redownloads, keep history and other useful features)

Maybe allow exposing a few YouTube-dl options.

**Comment by XiovV** [comment]
Thank you for the suggestions.
I started working on download history last night, all data is stored in a json file, at least for now.

By naming convention field do you mean that there should be an input field where you can specify exactly how to store the download?

**Comment by xInsertx** [comment]
@XiovV Yes, so with youtube-dl I would set the folder path relative to the download folder. something like /%channel%/%videotitle% - %year% - %videourl%

You could either a) make a cutdown version (options/templates you provide via dropdown), b) expose youtube-dl --output switch

Also, I just thought about it, maybe an option to embed or save each video's metadata and subs (if available).

I guess I could see this project potential as a simple webui that combines youtube-dl with really basic sonarr like management. I know there is def a want for that. Set and Forget that just works is King!

**Comment by XiovV** [comment]
Oh okay I understand now. Saving video metadata is another planned feature. The other one's you suggested are pretty useful too and will be added into the project, it's pretty difficult to project when though.

**Comment by xInsertx** [comment]
no rush, you're off to a great start, so I'm happy to wait =)

**Comment by XiovV** [comment]
Download history: implemented. Could use better UI, but will do for now.
