### ISSUE TITLE
Docker ARM support

### ISSUE THREAD

**Issue by 5hay** [XiovV/Golty#46]
**Is your feature request related to a problem? Please describe.**
The Docker image unfortunately does not support the ARM architecture which means that the image does not work on a Raspberry Pi.

**Describe the solution you'd like**
A Dockerfile.armhf :)

**Comment by biodrone** [comment]
There's nothing in the Dockerfile that specifically build x86. What error do you get when you build it on ARMHF?

**Comment by 5hay** [comment]
I think it's because of the ffmpeg image. The other two (ubuntu, golang) have ARM targets.

Just getting the default `exec` error that tells it's built for another arch.

**Comment by biodrone** [comment]
Fair enough, I'll have a look into it later on. Thanks!

**Comment by biodrone** [comment]
PR is done. Once merged, you can either build Dockerfile.arm yourself or just do a docker pull xiovv/go-auto-yt. Because of the way that the manifest works, it should auto select the correct architecture for you based on the device you're pulling from. Feel free to ping me if there's any issues!
