### ISSUE TITLE
Quality for Video and Audio is wrong on Channels tab

### ISSUE THREAD

**Issue by catthehacker** [XiovV/Golty#52]
**Describe the bug**
The available quality is: best/worst/worst

**To Reproduce**
Open GoAutoYT, nagivate to Channels, change option to Audio and Video, select quality.

**Expected behavior**
It should be: best/medium/worst

**Screenshots**
![image](https://user-images.githubusercontent.com/31106839/70376874-d65a6280-1905-11ea-8caf-8220187ed570.png)

**Desktop (please complete the following information):**
 - OS: Docker on QNAP TS-963x

**Additional context**
n/a

**Comment by XiovV** [comment]
I fixed it. I just need to clean the code up a bit and then I'll push the changes.
