### ISSUE TITLE
playlist refresh time in hours

### ISSUE THREAD

**Issue by AMJidovu** [XiovV/Golty#54]
Using the docker version of the app when i try and update the playlist refresh time to 6 hours (well hours in general) i am getting the following error:

"There was an error parsing json: json: cannot unmarshal number into Go struct field CheckingIntervalPayload.CheckingInterval of type string"

Entering time in minutes seems fine though.

Note. I did create a xml template for the docker version and added it to Unraid store app. I will add issues/bugs that the users of Unraid find.

**Comment by agilob** [comment]
Same for other types of intervals.

**Comment by XiovV** [comment]
Thanks for letting me know. I should start writing more unit tests ASAP.

**Comment by XiovV** [comment]
Bug fixed and new version pushed.
