### ISSUE TITLE
spaces in commands

### ISSUE THREAD

**Issue by AMJidovu** [XiovV/Golty#56]
If I use "Enter custom youtube-dl output" and I use spaces like in the examples is not going to work.

/videos/%(release_date)s %(title)s [%(id)s].%(ext)s
or 
/videos/%(uploader)s - %(title)s.%(ext)s

If I replace the spaces with underscores, it works.

**Comment by XiovV** [comment]
Good thing is, I know why this is happening, bad thing is I might need to come up with a clever way to fix it.

**Comment by AMJidovu** [comment]
> Good thing is, I know why this is happening, bad thing is I might need to come up with a clever way to fix it.

Will wait patiently for a fix and if new issues are found by unraid users using the docker version I will add them to the issues.

**Comment by XiovV** [comment]
Great, thank you.

**Comment by XiovV** [comment]
Good news! I finished the feature, I'm doing a refactor and testing now so I should push a new version in a few hours if everything goes well.
