### ISSUE TITLE
directory creation error

### ISSUE THREAD

**Issue by demenzio** [XiovV/Golty#57]
By adding a playlist to the playlist download section - no costum path entered, downloaded videos will be stored as followed:
`/app/downloadsYTUSERNAME/PLAYLIST/[...]`
Instead of  `/app/downloads/YTUSERNAME/PLAYLIST/[...]`

Running as Docker Container xiovv/go-auto-yt:stable

**Comment by XiovV** [comment]
Oh, *facepalm*. Thanks for reporting.

**Comment by XiovV** [comment]
I just fixed it.
