### ISSUE TITLE
Docker image no longer starts

### ISSUE THREAD

**Issue by AMJidovu** [XiovV/Golty#73]
A fresh install of the docker image is no longer starting without manual creation of the config files.
The error given by docker logs:
```
time="2019-12-18T04:25:17Z" level=error msg="database.load: could not read file: open config/playlists.json: no such file or directory"

time="2019-12-18T04:25:17Z" level=fatal msg="<nil>"
```

In order to start the docker image I have to recreate all 3 config json files manually.

**Comment by XiovV** [comment]
Merged 0.5.8, should work fine now.
