### ISSUE TITLE
Error updating check interval

### ISSUE THREAD

**Issue by NotExpectYet** [XiovV/Golty#79]
**Describe the bug**
Logs show error, and UI doesn't allow updating check interval. 

{"level":"error","msg":"uploadCheckerChannels: GetCheckingInterval: empty target list","time":"2019-12-23T09:54:23Z"}

{"level":"error","msg":"uploadCheckerPlaylists: GetCheckingInterval: empty target list","time":"2019-12-23T09:54:23Z"}

**Comment by XiovV** [comment]
@NotExpectYet you have to add at least one channel before updating the checking interval.

**Comment by NotExpectYet** [comment]
Ahh thought as much, as the channels wouldn't add but see you've closed that too :) Will check out the new version
