### ISSUE TITLE
[question] I have finished building docker image from this program. How do I submit Dockerfile?

### ISSUE THREAD

**Issue by glahera** [XiovV/Golty#9]
I contacted XiovV on reddit and discussed a bit about building Docker image for this. Now that I have successfully built it (and it is also quite minimal, just 134 MB), how do I submit this Dockerfile?

**Comment by XiovV** [comment]
You need to submit a pull request. Guide on how to do it: [guide](https://yangsu.github.io/pull-request-tutorial/)
